# Generated by Django 4.2 on 2023-04-05 15:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0005_alter_livros_co_autor_alter_livros_data_cadastro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='data_cadastro',
            field=models.DateField(default=datetime.datetime(2023, 4, 5, 15, 43, 15, 975057, tzinfo=datetime.timezone.utc)),
        ),
    ]
