# Generated by Django 4.2 on 2023-04-05 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0006_alter_livros_data_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='data_cadastro',
            field=models.DateField(default=datetime.datetime(2023, 4, 5, 15, 44, 46, 552943, tzinfo=datetime.timezone.utc)),
        ),
    ]
