# Generated by Django 4.2 on 2023-04-12 20:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0013_emprestimos_avaliacao_alter_livros_data_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimos',
            name='data_devolucao',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 12, 20, 35, 9, 209467, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='emprestimos',
            name='data_emprestimo',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 12, 20, 35, 9, 209467, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='livros',
            name='data_cadastro',
            field=models.DateField(default=datetime.datetime(2023, 4, 12, 20, 35, 9, 208467, tzinfo=datetime.timezone.utc)),
        ),
    ]
