# Generated by Django 4.2 on 2023-04-18 00:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0015_alter_emprestimos_avaliacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='capa_livro'),
        ),
        migrations.AlterField(
            model_name='emprestimos',
            name='data_devolucao',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 18, 0, 23, 34, 265720, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='emprestimos',
            name='data_emprestimo',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 18, 0, 23, 34, 265720, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='livros',
            name='data_cadastro',
            field=models.DateField(default=datetime.datetime(2023, 4, 18, 0, 23, 34, 263721, tzinfo=datetime.timezone.utc)),
        ),
    ]
